### ISSUE TITLE
formula does not support vrrp_sync_group

### ISSUE THREAD

**Issue by cathode911** [salt-formulas/salt-formula-keepalived#15]
Formula does not support keepalived feature 'vrrp_sync_group'
Suggested pillar example:

```
keepalived:
  cluster:
  <omitted>
    vrrp_sync_group:
      anygroupname:
        - service1
        - service2
    vrrp_instance:
    <omitted>
```
